delete from topic_linked;
delete from topic;

INSERT INTO topic (id, name, parent_topic_id) VALUES (1, 'topic20',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (2, 'topic19',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (3, 'topic18',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (4, 'topic17',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (5, 'topic16',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (6, 'topic15',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (7, 'topic14',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (8, 'topic13',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (9, 'topic12',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (10, 'topic11',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (11, 'topic10',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (12, 'topic9',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (13, 'topic8',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (14, 'topic7',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (15, 'topic6',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (16, 'topic5',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (17, 'topic4',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (18, 'topic3',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (19, 'topic2',null);
INSERT INTO topic (id, name, parent_topic_id) VALUES (20, 'topic1',null);

update topic set parent_topic_id = 19 where id = 2;
update topic set parent_topic_id = 19 where id = 3;
update topic set parent_topic_id = 19 where id = 5;
update topic set parent_topic_id = 17 where id = 7;
update topic set parent_topic_id = 16 where id = 8;
update topic set parent_topic_id = 6 where id = 10;
update topic set parent_topic_id = 10 where id = 12;
update topic set parent_topic_id = 11 where id = 14;
update topic set parent_topic_id = 1 where id = 16;
update topic set parent_topic_id = 6 where id = 19;


INSERT INTO topic_linked(id, linked_id) VALUES (1, 12);
INSERT INTO topic_linked(id, linked_id) VALUES (2, 13);
INSERT INTO topic_linked(id, linked_id) VALUES (3, 14);
INSERT INTO topic_linked(id, linked_id) VALUES (4, 15);
INSERT INTO topic_linked(id, linked_id) VALUES (5, 16);
INSERT INTO topic_linked(id, linked_id) VALUES (6, 17);
INSERT INTO topic_linked(id, linked_id) VALUES (7, 18);
INSERT INTO topic_linked(id, linked_id) VALUES (8, 19);
INSERT INTO topic_linked(id, linked_id) VALUES (9, 20);
INSERT INTO topic_linked(id, linked_id) VALUES (10, 1);
INSERT INTO topic_linked(id, linked_id) VALUES (11, 2);
INSERT INTO topic_linked(id, linked_id) VALUES (12, 3);
INSERT INTO topic_linked(id, linked_id) VALUES (13, 4);
INSERT INTO topic_linked(id, linked_id) VALUES (14, 5);
INSERT INTO topic_linked(id, linked_id) VALUES (15, 6);
INSERT INTO topic_linked(id, linked_id) VALUES (16, 7);
INSERT INTO topic_linked(id, linked_id) VALUES (17, 8);
INSERT INTO topic_linked(id, linked_id) VALUES (18, 9);
INSERT INTO topic_linked(id, linked_id) VALUES (19, 10);
INSERT INTO topic_linked(id, linked_id) VALUES (20, 11);
INSERT INTO topic_linked(id, linked_id) VALUES (20, 12);
INSERT INTO topic_linked(id, linked_id) VALUES (20, 13);
INSERT INTO topic_linked(id, linked_id) VALUES (20, 14);
INSERT INTO topic_linked(id, linked_id) VALUES (14, 18);
INSERT INTO topic_linked(id, linked_id) VALUES (15, 18);
INSERT INTO topic_linked(id, linked_id) VALUES (15, 6);
INSERT INTO topic_linked(id, linked_id) VALUES (15, 7);
INSERT INTO topic_linked(id, linked_id) VALUES (15, 14);
INSERT INTO topic_linked(id, linked_id) VALUES (18, 19);
INSERT INTO topic_linked(id, linked_id) VALUES (18, 20);
INSERT INTO topic_linked(id, linked_id) VALUES (18, 17);